name: hair_salon
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
  # Added dependencies for the salon app
  google_fonts: ^6.1.0
  flutter_screenutil: ^5.9.0
  flutter_animate: ^4.3.0
  provider: ^6.1.1
  smooth_page_indicator: ^1.1.0
  shared_preferences: ^2.2.2
  table_calendar: ^3.0.9
  
  # Additional dependencies for authentication
  flutter_svg: ^2.0.9
  pin_code_fields: ^8.0.1
  email_validator: ^2.1.17
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
